-- MySQL Script generated by MySQL Workbench
-- 02/01/17 11:15:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sc_servcomapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sc_servcomapp` ;

-- -----------------------------------------------------
-- Schema sc_servcomapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sc_servcomapp` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `sc_servcomapp` ;

-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_usuarios` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_usuarios` (
  `us_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `us_apodo` VARCHAR(45) NOT NULL,
  `us_clave` VARCHAR(45) NOT NULL,
  `us_tipo` ENUM('admin', 'coord', 'tutor', 'estudiante') NOT NULL DEFAULT 'estudiante',
  `us_nombre` VARCHAR(45) NOT NULL,
  `us_fechaCreacion` DATE NOT NULL,
  `us_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `us_id_UNIQUE` ON `sc_servcomapp`.`sc_usuarios` (`us_id` ASC);

CREATE UNIQUE INDEX `us_apodo_UNIQUE` ON `sc_servcomapp`.`sc_usuarios` (`us_apodo` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_personas` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_personas` (
  `sc_usuarios_us_id` INT UNSIGNED NOT NULL,
  `pe_cedula` VARCHAR(20) NOT NULL,
  `pe_nombre` VARCHAR(45) NOT NULL,
  `pe_apellido` VARCHAR(45) NOT NULL,
  `pe_correo` VARCHAR(100) NOT NULL,
  `pe_fechaNac` DATE NULL,
  `pe_telefono` VARCHAR(13) NULL,
  `pe_direccion` VARCHAR(200) NULL,
  `pe_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`pe_cedula`, `sc_usuarios_us_id`),
  CONSTRAINT `fk_sc_personas_sc_usuarios`
    FOREIGN KEY (`sc_usuarios_us_id`)
    REFERENCES `sc_servcomapp`.`sc_usuarios` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sc_personas_sc_usuarios_idx` ON `sc_servcomapp`.`sc_personas` (`sc_usuarios_us_id` ASC);

CREATE UNIQUE INDEX `sc_usuarios_us_id_UNIQUE` ON `sc_servcomapp`.`sc_personas` (`sc_usuarios_us_id` ASC);

CREATE UNIQUE INDEX `pe_cedula_UNIQUE` ON `sc_servcomapp`.`sc_personas` (`pe_cedula` ASC);

CREATE UNIQUE INDEX `pe_correo_UNIQUE` ON `sc_servcomapp`.`sc_personas` (`pe_correo` ASC);

CREATE UNIQUE INDEX `pe_telefono_UNIQUE` ON `sc_servcomapp`.`sc_personas` (`pe_telefono` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_facultades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_facultades` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_facultades` (
  `fa_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fa_nombre` VARCHAR(45) NOT NULL,
  `fa_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`fa_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `fa_id_UNIQUE` ON `sc_servcomapp`.`sc_facultades` (`fa_id` ASC);

CREATE UNIQUE INDEX `fa_nombre_UNIQUE` ON `sc_servcomapp`.`sc_facultades` (`fa_nombre` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_carreras` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_carreras` (
  `ca_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sc_facultades_fa_id` INT UNSIGNED NOT NULL,
  `ca_nombre` VARCHAR(45) NOT NULL,
  `ca_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ca_id`, `sc_facultades_fa_id`),
  CONSTRAINT `fk_sc_carreras_sc_facultades1`
    FOREIGN KEY (`sc_facultades_fa_id`)
    REFERENCES `sc_servcomapp`.`sc_facultades` (`fa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sc_carreras_sc_facultades1_idx` ON `sc_servcomapp`.`sc_carreras` (`sc_facultades_fa_id` ASC);

CREATE UNIQUE INDEX `ca_id_UNIQUE` ON `sc_servcomapp`.`sc_carreras` (`ca_id` ASC);

CREATE UNIQUE INDEX `ca_nombre_UNIQUE` ON `sc_servcomapp`.`sc_carreras` (`ca_nombre` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_estudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_estudiantes` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_estudiantes` (
  `sc_personas_pe_cedula` VARCHAR(20) NOT NULL,
  `sc_carreras_ca_id` INT UNSIGNED NOT NULL,
  `es_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`sc_personas_pe_cedula`, `sc_carreras_ca_id`),
  CONSTRAINT `fk_sc_estudiantes_sc_personas1`
    FOREIGN KEY (`sc_personas_pe_cedula`)
    REFERENCES `sc_servcomapp`.`sc_personas` (`pe_cedula`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sc_estudiantes_sc_carreras1`
    FOREIGN KEY (`sc_carreras_ca_id`)
    REFERENCES `sc_servcomapp`.`sc_carreras` (`ca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sc_estudiantes_sc_carreras1_idx` ON `sc_servcomapp`.`sc_estudiantes` (`sc_carreras_ca_id` ASC);

CREATE UNIQUE INDEX `sc_personas_pe_cedula_UNIQUE` ON `sc_servcomapp`.`sc_estudiantes` (`sc_personas_pe_cedula` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_institucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_institucion` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_institucion` (
  `inst_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inst_nombre` VARCHAR(100) NOT NULL,
  `inst_telefono` VARCHAR(13) NULL,
  `inst_correo` VARCHAR(60) NULL,
  `inst_url` VARCHAR(70) NULL,
  `inst_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`inst_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `inst_id_UNIQUE` ON `sc_servcomapp`.`sc_institucion` (`inst_id` ASC);

CREATE UNIQUE INDEX `inst_telefono_UNIQUE` ON `sc_servcomapp`.`sc_institucion` (`inst_telefono` ASC);

CREATE UNIQUE INDEX `inst_correo_UNIQUE` ON `sc_servcomapp`.`sc_institucion` (`inst_correo` ASC);

CREATE UNIQUE INDEX `inst_url_UNIQUE` ON `sc_servcomapp`.`sc_institucion` (`inst_url` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_tutores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_tutores` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_tutores` (
  `sc_personas_pe_cedula` VARCHAR(20) NOT NULL,
  `sc_institucion_inst_id` INT UNSIGNED NOT NULL,
  `tu_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`sc_personas_pe_cedula`),
  CONSTRAINT `fk_sc_tutores_sc_personas1`
    FOREIGN KEY (`sc_personas_pe_cedula`)
    REFERENCES `sc_servcomapp`.`sc_personas` (`pe_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sc_tutores_sc_institucion1`
    FOREIGN KEY (`sc_institucion_inst_id`)
    REFERENCES `sc_servcomapp`.`sc_institucion` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sc_tutores_sc_institucion1_idx` ON `sc_servcomapp`.`sc_tutores` (`sc_institucion_inst_id` ASC);

CREATE UNIQUE INDEX `sc_personas_pe_cedula_UNIQUE` ON `sc_servcomapp`.`sc_tutores` (`sc_personas_pe_cedula` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_coordinadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_coordinadores` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_coordinadores` (
  `sc_personas_pe_cedula` VARCHAR(20) NOT NULL,
  `sc_facultades_fa_id` INT UNSIGNED NOT NULL,
  `co_oficina` VARCHAR(100) NOT NULL,
  `co_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`sc_personas_pe_cedula`, `sc_facultades_fa_id`),
  CONSTRAINT `fk_sc_coordinadores_sc_personas1`
    FOREIGN KEY (`sc_personas_pe_cedula`)
    REFERENCES `sc_servcomapp`.`sc_personas` (`pe_cedula`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sc_coordinadores_sc_facultades1`
    FOREIGN KEY (`sc_facultades_fa_id`)
    REFERENCES `sc_servcomapp`.`sc_facultades` (`fa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sc_coordinadores_sc_facultades1_idx` ON `sc_servcomapp`.`sc_coordinadores` (`sc_facultades_fa_id` ASC);

CREATE UNIQUE INDEX `sc_personas_pe_cedula_UNIQUE` ON `sc_servcomapp`.`sc_coordinadores` (`sc_personas_pe_cedula` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_programas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_programas` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_programas` (
  `prog_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prog_nombre` VARCHAR(60) NOT NULL,
  `prog_objGen` VARCHAR(200) NOT NULL,
  `prog_objEsp` VARCHAR(400) NULL,
  `prog_fechaCreacion` DATE NOT NULL,
  `prog_fechaActualizacion` DATE NOT NULL,
  `sc_facultades_fa_id` INT UNSIGNED NOT NULL,
  `prog_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`prog_id`, `sc_facultades_fa_id`),
  CONSTRAINT `fk_programas_sc_facultades1`
    FOREIGN KEY (`sc_facultades_fa_id`)
    REFERENCES `sc_servcomapp`.`sc_facultades` (`fa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_programas_sc_facultades1_idx` ON `sc_servcomapp`.`sc_programas` (`sc_facultades_fa_id` ASC);

CREATE UNIQUE INDEX `prog_id_UNIQUE` ON `sc_servcomapp`.`sc_programas` (`prog_id` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_proyectos` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_proyectos` (
  `proy_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sc_programas_prog_id` INT UNSIGNED NOT NULL,
  `proy_nombre` VARCHAR(45) NOT NULL,
  `proy_ubicacion` VARCHAR(200) NOT NULL,
  `proy_actividades` TEXT(1000) NOT NULL,
  `sc_tutores_sc_personas_pe_cedula` VARCHAR(20) NOT NULL,
  `proy_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`proy_id`, `sc_programas_prog_id`),
  CONSTRAINT `fk_sc_proyectos_sc_programas1`
    FOREIGN KEY (`sc_programas_prog_id`)
    REFERENCES `sc_servcomapp`.`sc_programas` (`prog_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sc_proyectos_sc_tutores1`
    FOREIGN KEY (`sc_tutores_sc_personas_pe_cedula`)
    REFERENCES `sc_servcomapp`.`sc_tutores` (`sc_personas_pe_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sc_proyectos_sc_programas1_idx` ON `sc_servcomapp`.`sc_proyectos` (`sc_programas_prog_id` ASC);

CREATE INDEX `fk_sc_proyectos_sc_tutores1_idx` ON `sc_servcomapp`.`sc_proyectos` (`sc_tutores_sc_personas_pe_cedula` ASC);

CREATE UNIQUE INDEX `proy_id_UNIQUE` ON `sc_servcomapp`.`sc_proyectos` (`proy_id` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_detalle_proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_detalle_proyecto` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_detalle_proyecto` (
  `pd_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sc_proyectos_proy_id` INT UNSIGNED NOT NULL,
  `pd_capacity` INT NOT NULL,
  `sc_carreras_ca_id` INT UNSIGNED NOT NULL,
  `pd_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`pd_id`, `sc_proyectos_proy_id`),
  CONSTRAINT `fk_sc_detalle_proyecto_sc_carreras1`
    FOREIGN KEY (`sc_carreras_ca_id`)
    REFERENCES `sc_servcomapp`.`sc_carreras` (`ca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sc_detalle_proyecto_sc_proyectos1`
    FOREIGN KEY (`sc_proyectos_proy_id`)
    REFERENCES `sc_servcomapp`.`sc_proyectos` (`proy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sc_detalle_proyecto_sc_carreras1_idx` ON `sc_servcomapp`.`sc_detalle_proyecto` (`sc_carreras_ca_id` ASC);

CREATE INDEX `fk_sc_detalle_proyecto_sc_proyectos1_idx` ON `sc_servcomapp`.`sc_detalle_proyecto` (`sc_proyectos_proy_id` ASC);

CREATE UNIQUE INDEX `pd_id_UNIQUE` ON `sc_servcomapp`.`sc_detalle_proyecto` (`pd_id` ASC);


-- -----------------------------------------------------
-- Table `sc_servcomapp`.`sc_inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc_servcomapp`.`sc_inscripcion` ;

CREATE TABLE IF NOT EXISTS `sc_servcomapp`.`sc_inscripcion` (
  `insc_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `insc_semestre` VARCHAR(10) NOT NULL,
  `insc_estado_actual` ENUM('1', '2', '3', '4') NOT NULL DEFAULT '1',
  `sc_estudiantes_sc_personas_cedula` VARCHAR(20) NOT NULL,
  `sc_proyectos_proy_id` INT UNSIGNED NOT NULL,
  `sc_proyectos_sc_programas_prog_id` INT UNSIGNED NOT NULL,
  `insc_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`insc_id`),
  CONSTRAINT `fk_sc_inscripcion_sc_estudiantes1`
    FOREIGN KEY (`sc_estudiantes_sc_personas_cedula`)
    REFERENCES `sc_servcomapp`.`sc_estudiantes` (`sc_personas_pe_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sc_inscripcion_sc_proyectos1`
    FOREIGN KEY (`sc_proyectos_proy_id` , `sc_proyectos_sc_programas_prog_id`)
    REFERENCES `sc_servcomapp`.`sc_proyectos` (`proy_id` , `sc_programas_prog_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sc_inscripcion_sc_estudiantes1_idx` ON `sc_servcomapp`.`sc_inscripcion` (`sc_estudiantes_sc_personas_cedula` ASC);

CREATE INDEX `fk_sc_inscripcion_sc_proyectos1_idx` ON `sc_servcomapp`.`sc_inscripcion` (`sc_proyectos_proy_id` ASC, `sc_proyectos_sc_programas_prog_id` ASC);

CREATE UNIQUE INDEX `insc_id_UNIQUE` ON `sc_servcomapp`.`sc_inscripcion` (`insc_id` ASC);

CREATE UNIQUE INDEX `sc_estudiantes_sc_personas_cedula_UNIQUE` ON `sc_servcomapp`.`sc_inscripcion` (`sc_estudiantes_sc_personas_cedula` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `sc_servcomapp`.`sc_facultades`  (`fa_id`,  `fa_nombre`, `fa_status`) VALUES  (NULL, 'f_ingenieria', '1'), (NULL, 'f_csociales', '1'), (NULL, 'f_ceducacion', '1'), (NULL, 'f_csalud', '1'), (NULL, 'f_cjurpol', '1');

INSERT INTO `sc_servcomapp`.`sc_carreras` (`ca_id`, `sc_facultades_fa_id`, `ca_nombre`, `ca_status`) VALUES (NULL, '1', 'arquitectura', '1'), (NULL, '1', 'i_computacion', '1'),  (NULL, '1', 'i_civil', '1'),  (NULL, '1', 'i_industrial', '1'), (NULL, '1', 'i_electronica', '1'), (NULL, '1', 'i_mecanica', '1') , (NULL, '1', 'i_telecomunicacion', '1'), (NULL, '2', 'a_empresas', '1'), (NULL, '2', 'a_publica', '1'), (NULL, '2', 'c_publica', '1'), (NULL, '2', 'mercadeo', '1'), (NULL, '2', 'r_industriales', '1'), (NULL, '3', 'informatica', '1'), (NULL, '3', 'integral', '1'), (NULL, '3', 'preescolar', '1'), (NULL, '4', 'odontologia', '1'), (NULL, '5', 'derecho', '1');

